export interface TopicCategory {
  name: string;
  borderColor: string;
  activeBorderColor: string;
  topics: {
    name: string;
    storyCount?: string;
  }[];
}

export const ONBOARDING_CATEGORIES: TopicCategory[] = [
  {
    name: "Technology",
    borderColor: "border-[#D0E1F9]",
    activeBorderColor: "border-[#2563EB]",
    topics: [
      { name: "Technology", storyCount: "4.2M" },
      { name: "AI", storyCount: "1.8M" },
      { name: "Artificial Intelligence", storyCount: "950K" },
      { name: "Cybersecurity", storyCount: "340K" },
      { name: "AWS", storyCount: "420K" },
      { name: "LLM", storyCount: "680K" },
      { name: "ChatGPT", storyCount: "820K" },
      { name: "UX", storyCount: "510K" },
      { name: "UX Design", storyCount: "490K" },
      { name: "Android", storyCount: "290K" },
      { name: "iOS", storyCount: "310K" },
      { name: "Apple", storyCount: "440K" },
      { name: "AI Agent", storyCount: "190K" },
      { name: "Future", storyCount: "520K" },
      { name: "Tech", storyCount: "1.1M" },
      { name: "Kubernetes", storyCount: "270K" },
    ],
  },
  {
    name: "Programming",
    borderColor: "border-[#D1F0DE]",
    activeBorderColor: "border-[#059669]",
    topics: [
      { name: "Programming", storyCount: "3.5M" },
      { name: "Data Science", storyCount: "2.1M" },
      { name: "Software Development", storyCount: "1.9M" },
      { name: "Python", storyCount: "2.8M" },
      { name: "Software Engineering", storyCount: "1.4M" },
      { name: "Machine Learning", storyCount: "2.3M" },
      { name: "DevOps", storyCount: "620K" },
      { name: "Web Development", storyCount: "1.7M" },
      { name: "Data Engineering", storyCount: "410K" },
      { name: "Java", storyCount: "890K" },
      { name: "JavaScript", storyCount: "2.4M" },
      { name: "Flutter", storyCount: "380K" },
      { name: "Deep Learning", storyCount: "780K" },
      { name: "React", storyCount: "1.2M" },
    ],
  },
  {
    name: "Wellness",
    borderColor: "border-[#FCD7E4]",
    activeBorderColor: "border-[#DB2777]",
    topics: [
      { name: "Psychology", storyCount: "1.5M" },
      { name: "Self Improvement", storyCount: "3.1M" },
      { name: "Mental Health", storyCount: "1.2M" },
      { name: "Productivity", storyCount: "2.2M" },
      { name: "Spirituality", storyCount: "680K" },
      { name: "Personal Growth", storyCount: "1.8M" },
      { name: "Wellness", storyCount: "940K" },
      { name: "Mindfulness", storyCount: "820K" },
      { name: "Fitness", storyCount: "650K" },
      { name: "Personal Development", storyCount: "1.1M" },
      { name: "Motivation", storyCount: "790K" },
      { name: "Sports", storyCount: "410K" },
    ],
  },
  {
    name: "Life",
    borderColor: "border-[#FCE5B8]",
    activeBorderColor: "border-[#D97706]",
    topics: [
      { name: "Life", storyCount: "2.9M" },
      { name: "Relationships", storyCount: "1.6M" },
      { name: "Love", storyCount: "1.3M" },
      { name: "Life Lessons", storyCount: "2.4M" },
      { name: "Health", storyCount: "1.5M" },
      { name: "This Happened To Me", storyCount: "870K" },
      { name: "Travel", storyCount: "980K" },
      { name: "Lifestyle", storyCount: "840K" },
      { name: "Family", storyCount: "620K" },
      { name: "Parenting", storyCount: "540K" },
      { name: "Faith", storyCount: "430K" },
      { name: "Healing", storyCount: "390K" },
      { name: "Sexuality", storyCount: "310K" },
    ],
  },
  {
    name: "Society",
    borderColor: "border-[#D5E3F8]",
    activeBorderColor: "border-[#2563EB]",
    topics: [
      { name: "Politics", storyCount: "1.9M" },
      { name: "Women", storyCount: "780K" },
      { name: "History", storyCount: "1.1M" },
      { name: "Society", storyCount: "920K" },
      { name: "News", storyCount: "840K" },
      { name: "War", storyCount: "420K" },
      { name: "Economics", storyCount: "760K" },
      { name: "Religion", storyCount: "530K" },
      { name: "Christianity", storyCount: "370K" },
      { name: "Feminism", storyCount: "490K" },
      { name: "Geopolitics", storyCount: "380K" },
      { name: "World", storyCount: "670K" },
      { name: "Justice", storyCount: "310K" },
      { name: "Equality", storyCount: "280K" },
      { name: "Ukraine War", storyCount: "290K" },
    ],
  },
  {
    name: "Culture",
    borderColor: "border-[#E3DAFC]",
    activeBorderColor: "border-[#7C3AED]",
    topics: [
      { name: "Science", storyCount: "1.3M" },
      { name: "Writing", storyCount: "2.5M" },
      { name: "Culture", storyCount: "1.7M" },
      { name: "Philosophy", storyCount: "980K" },
      { name: "Education", storyCount: "870K" },
      { name: "Books", storyCount: "1.2M" },
      { name: "Humor", storyCount: "630K" },
      { name: "Space", storyCount: "450K" },
      { name: "Inspiration", storyCount: "890K" },
      { name: "Creativity", storyCount: "1.4M" },
      { name: "Art", storyCount: "960K" },
      { name: "Music", storyCount: "810K" },
      { name: "Gaming", storyCount: "540K" },
      { name: "Math", storyCount: "320K" },
    ],
  },
  {
    name: "Business",
    borderColor: "border-[#CCEAF5]",
    activeBorderColor: "border-[#0284C7]",
    topics: [
      { name: "Business", storyCount: "3.2M" },
      { name: "Money", storyCount: "1.9M" },
      { name: "Entrepreneurship", storyCount: "2.1M" },
      { name: "Leadership", storyCount: "1.5M" },
      { name: "Startup", storyCount: "1.8M" },
      { name: "Careers", storyCount: "1.3M" },
      { name: "Finance", storyCount: "1.4M" },
      { name: "Investing", storyCount: "1.2M" },
      { name: "Work", storyCount: "1.1M" },
      { name: "Marketing", storyCount: "1.6M" },
      { name: "Cryptocurrency", storyCount: "980K" },
    ],
  },
];
